//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.15 at 12:39:23 PM ADT 
//


package com.jrodolfo.weather.model.jaxbgenerated.site;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for currentConditionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="currentConditionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="station" type="{}stationType"/>
 *         &lt;element name="dateTime" type="{}dateStampType" maxOccurs="2" minOccurs="2"/>
 *         &lt;element name="condition" type="{}conditionType"/>
 *         &lt;element name="iconCode" type="{}iconCodeType"/>
 *         &lt;element name="temperature" type="{}temperatureType"/>
 *         &lt;element name="dewpoint" type="{}temperatureType"/>
 *         &lt;element name="windChill" type="{}calculatedWindChillType" minOccurs="0"/>
 *         &lt;element name="humidex" type="{}calculatedHumidexType" minOccurs="0"/>
 *         &lt;element name="pressure" type="{}pressureTypeCond"/>
 *         &lt;element name="visibility" type="{}visibilityTypeCond"/>
 *         &lt;element name="relativeHumidity" type="{}relativeHumidityType"/>
 *         &lt;element name="wind" type="{}windType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "currentConditionsType", propOrder = {
    "station",
    "dateTime",
    "condition",
    "iconCode",
    "temperature",
    "dewpoint",
    "windChill",
    "humidex",
    "pressure",
    "visibility",
    "relativeHumidity",
    "wind"
})
public class CurrentConditionsType {

    @XmlElement(required = true)
    protected StationType station;
    @XmlElement(required = true)
    protected List<DateStampType> dateTime;
    @XmlElement(required = true)
    protected String condition;
    @XmlElement(required = true)
    protected IconCodeType iconCode;
    @XmlElement(required = true)
    protected TemperatureType temperature;
    @XmlElement(required = true)
    protected TemperatureType dewpoint;
    protected CalculatedWindChillType windChill;
    protected CalculatedHumidexType humidex;
    @XmlElement(required = true)
    protected PressureTypeCond pressure;
    @XmlElement(required = true)
    protected VisibilityTypeCond visibility;
    @XmlElement(required = true)
    protected RelativeHumidityType relativeHumidity;
    @XmlElement(required = true)
    protected WindType wind;

    /**
     * Gets the value of the station property.
     * 
     * @return
     *     possible object is
     *     {@link StationType }
     *     
     */
    public StationType getStation() {
        return station;
    }

    /**
     * Sets the value of the station property.
     * 
     * @param value
     *     allowed object is
     *     {@link StationType }
     *     
     */
    public void setStation(StationType value) {
        this.station = value;
    }

    /**
     * Gets the value of the dateTime property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dateTime property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDateTime().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DateStampType }
     * 
     * 
     */
    public List<DateStampType> getDateTime() {
        if (dateTime == null) {
            dateTime = new ArrayList<DateStampType>();
        }
        return this.dateTime;
    }

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCondition(String value) {
        this.condition = value;
    }

    /**
     * Gets the value of the iconCode property.
     * 
     * @return
     *     possible object is
     *     {@link IconCodeType }
     *     
     */
    public IconCodeType getIconCode() {
        return iconCode;
    }

    /**
     * Sets the value of the iconCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link IconCodeType }
     *     
     */
    public void setIconCode(IconCodeType value) {
        this.iconCode = value;
    }

    /**
     * Gets the value of the temperature property.
     * 
     * @return
     *     possible object is
     *     {@link TemperatureType }
     *     
     */
    public TemperatureType getTemperature() {
        return temperature;
    }

    /**
     * Sets the value of the temperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemperatureType }
     *     
     */
    public void setTemperature(TemperatureType value) {
        this.temperature = value;
    }

    /**
     * Gets the value of the dewpoint property.
     * 
     * @return
     *     possible object is
     *     {@link TemperatureType }
     *     
     */
    public TemperatureType getDewpoint() {
        return dewpoint;
    }

    /**
     * Sets the value of the dewpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemperatureType }
     *     
     */
    public void setDewpoint(TemperatureType value) {
        this.dewpoint = value;
    }

    /**
     * Gets the value of the windChill property.
     * 
     * @return
     *     possible object is
     *     {@link CalculatedWindChillType }
     *     
     */
    public CalculatedWindChillType getWindChill() {
        return windChill;
    }

    /**
     * Sets the value of the windChill property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalculatedWindChillType }
     *     
     */
    public void setWindChill(CalculatedWindChillType value) {
        this.windChill = value;
    }

    /**
     * Gets the value of the humidex property.
     * 
     * @return
     *     possible object is
     *     {@link CalculatedHumidexType }
     *     
     */
    public CalculatedHumidexType getHumidex() {
        return humidex;
    }

    /**
     * Sets the value of the humidex property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalculatedHumidexType }
     *     
     */
    public void setHumidex(CalculatedHumidexType value) {
        this.humidex = value;
    }

    /**
     * Gets the value of the pressure property.
     * 
     * @return
     *     possible object is
     *     {@link PressureTypeCond }
     *     
     */
    public PressureTypeCond getPressure() {
        return pressure;
    }

    /**
     * Sets the value of the pressure property.
     * 
     * @param value
     *     allowed object is
     *     {@link PressureTypeCond }
     *     
     */
    public void setPressure(PressureTypeCond value) {
        this.pressure = value;
    }

    /**
     * Gets the value of the visibility property.
     * 
     * @return
     *     possible object is
     *     {@link VisibilityTypeCond }
     *     
     */
    public VisibilityTypeCond getVisibility() {
        return visibility;
    }

    /**
     * Sets the value of the visibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisibilityTypeCond }
     *     
     */
    public void setVisibility(VisibilityTypeCond value) {
        this.visibility = value;
    }

    /**
     * Gets the value of the relativeHumidity property.
     * 
     * @return
     *     possible object is
     *     {@link RelativeHumidityType }
     *     
     */
    public RelativeHumidityType getRelativeHumidity() {
        return relativeHumidity;
    }

    /**
     * Sets the value of the relativeHumidity property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelativeHumidityType }
     *     
     */
    public void setRelativeHumidity(RelativeHumidityType value) {
        this.relativeHumidity = value;
    }

    /**
     * Gets the value of the wind property.
     * 
     * @return
     *     possible object is
     *     {@link WindType }
     *     
     */
    public WindType getWind() {
        return wind;
    }

    /**
     * Sets the value of the wind property.
     * 
     * @param value
     *     allowed object is
     *     {@link WindType }
     *     
     */
    public void setWind(WindType value) {
        this.wind = value;
    }

}
