//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.15 at 12:39:23 PM ADT 
//


package com.jrodolfo.weather.model.jaxbgenerated.site;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for forecastGroupTypeFull complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="forecastGroupTypeFull">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dateTime" type="{}dateStampType" maxOccurs="2" minOccurs="2"/>
 *         &lt;element name="regionalNormals" type="{}regionalNormalsType"/>
 *         &lt;element name="forecast" type="{}forecastTypeFull" maxOccurs="6" minOccurs="6"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "forecastGroupTypeFull", propOrder = {
    "dateTime",
    "regionalNormals",
    "forecast"
})
public class ForecastGroupTypeFull {

    @XmlElement(required = true)
    protected List<DateStampType> dateTime;
    @XmlElement(required = true)
    protected RegionalNormalsType regionalNormals;
    @XmlElement(required = true)
    protected List<ForecastTypeFull> forecast;

    /**
     * Gets the value of the dateTime property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dateTime property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDateTime().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DateStampType }
     * 
     * 
     */
    public List<DateStampType> getDateTime() {
        if (dateTime == null) {
            dateTime = new ArrayList<DateStampType>();
        }
        return this.dateTime;
    }

    /**
     * Gets the value of the regionalNormals property.
     * 
     * @return
     *     possible object is
     *     {@link RegionalNormalsType }
     *     
     */
    public RegionalNormalsType getRegionalNormals() {
        return regionalNormals;
    }

    /**
     * Sets the value of the regionalNormals property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegionalNormalsType }
     *     
     */
    public void setRegionalNormals(RegionalNormalsType value) {
        this.regionalNormals = value;
    }

    /**
     * Gets the value of the forecast property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the forecast property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getForecast().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ForecastTypeFull }
     * 
     * 
     */
    public List<ForecastTypeFull> getForecast() {
        if (forecast == null) {
            forecast = new ArrayList<ForecastTypeFull>();
        }
        return this.forecast;
    }

}
