//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.15 at 12:39:23 PM ADT 
//


package com.jrodolfo.weather.model.jaxbgenerated.site;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for forecastTypeFull complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="forecastTypeFull">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="period" type="{}periodType"/>
 *         &lt;element name="textSummary" type="{}textSummaryType"/>
 *         &lt;element name="cloudPrecip" type="{}cloudPrecipType"/>
 *         &lt;element name="abbreviatedForecast" type="{}abbreviatedForecastType"/>
 *         &lt;element name="temperatures" type="{}temperaturesType"/>
 *         &lt;element name="winds" type="{}windsType"/>
 *         &lt;element name="precipitation" type="{}precipTypeForecast"/>
 *         &lt;element name="snowLevel" type="{}snowLevelType" minOccurs="0"/>
 *         &lt;element name="windChill" type="{}windChillType" minOccurs="0"/>
 *         &lt;element name="visibility" type="{}visibilityTypeForecast" minOccurs="0"/>
 *         &lt;element name="uv" type="{}uvType" minOccurs="0"/>
 *         &lt;element name="relativeHumidity" type="{}relativeHumidityType" minOccurs="0"/>
 *         &lt;element name="comfort" type="{}comfortType" minOccurs="0"/>
 *         &lt;element name="frost" type="{}frostType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "forecastTypeFull", propOrder = {
    "period",
    "textSummary",
    "cloudPrecip",
    "abbreviatedForecast",
    "temperatures",
    "winds",
    "precipitation",
    "snowLevel",
    "windChill",
    "visibility",
    "uv",
    "relativeHumidity",
    "comfort",
    "frost"
})
public class ForecastTypeFull {

    @XmlElement(required = true)
    protected PeriodType period;
    @XmlElement(required = true)
    protected String textSummary;
    @XmlElement(required = true)
    protected CloudPrecipType cloudPrecip;
    @XmlElement(required = true)
    protected AbbreviatedForecastType abbreviatedForecast;
    @XmlElement(required = true)
    protected TemperaturesType temperatures;
    @XmlElement(required = true)
    protected WindsType winds;
    @XmlElement(required = true)
    protected PrecipTypeForecast precipitation;
    protected SnowLevelType snowLevel;
    protected WindChillType windChill;
    protected VisibilityTypeForecast visibility;
    protected UvType uv;
    protected RelativeHumidityType relativeHumidity;
    protected ComfortType comfort;
    protected FrostType frost;

    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link PeriodType }
     *     
     */
    public PeriodType getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodType }
     *     
     */
    public void setPeriod(PeriodType value) {
        this.period = value;
    }

    /**
     * Gets the value of the textSummary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextSummary() {
        return textSummary;
    }

    /**
     * Sets the value of the textSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextSummary(String value) {
        this.textSummary = value;
    }

    /**
     * Gets the value of the cloudPrecip property.
     * 
     * @return
     *     possible object is
     *     {@link CloudPrecipType }
     *     
     */
    public CloudPrecipType getCloudPrecip() {
        return cloudPrecip;
    }

    /**
     * Sets the value of the cloudPrecip property.
     * 
     * @param value
     *     allowed object is
     *     {@link CloudPrecipType }
     *     
     */
    public void setCloudPrecip(CloudPrecipType value) {
        this.cloudPrecip = value;
    }

    /**
     * Gets the value of the abbreviatedForecast property.
     * 
     * @return
     *     possible object is
     *     {@link AbbreviatedForecastType }
     *     
     */
    public AbbreviatedForecastType getAbbreviatedForecast() {
        return abbreviatedForecast;
    }

    /**
     * Sets the value of the abbreviatedForecast property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbbreviatedForecastType }
     *     
     */
    public void setAbbreviatedForecast(AbbreviatedForecastType value) {
        this.abbreviatedForecast = value;
    }

    /**
     * Gets the value of the temperatures property.
     * 
     * @return
     *     possible object is
     *     {@link TemperaturesType }
     *     
     */
    public TemperaturesType getTemperatures() {
        return temperatures;
    }

    /**
     * Sets the value of the temperatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemperaturesType }
     *     
     */
    public void setTemperatures(TemperaturesType value) {
        this.temperatures = value;
    }

    /**
     * Gets the value of the winds property.
     * 
     * @return
     *     possible object is
     *     {@link WindsType }
     *     
     */
    public WindsType getWinds() {
        return winds;
    }

    /**
     * Sets the value of the winds property.
     * 
     * @param value
     *     allowed object is
     *     {@link WindsType }
     *     
     */
    public void setWinds(WindsType value) {
        this.winds = value;
    }

    /**
     * Gets the value of the precipitation property.
     * 
     * @return
     *     possible object is
     *     {@link PrecipTypeForecast }
     *     
     */
    public PrecipTypeForecast getPrecipitation() {
        return precipitation;
    }

    /**
     * Sets the value of the precipitation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrecipTypeForecast }
     *     
     */
    public void setPrecipitation(PrecipTypeForecast value) {
        this.precipitation = value;
    }

    /**
     * Gets the value of the snowLevel property.
     * 
     * @return
     *     possible object is
     *     {@link SnowLevelType }
     *     
     */
    public SnowLevelType getSnowLevel() {
        return snowLevel;
    }

    /**
     * Sets the value of the snowLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link SnowLevelType }
     *     
     */
    public void setSnowLevel(SnowLevelType value) {
        this.snowLevel = value;
    }

    /**
     * Gets the value of the windChill property.
     * 
     * @return
     *     possible object is
     *     {@link WindChillType }
     *     
     */
    public WindChillType getWindChill() {
        return windChill;
    }

    /**
     * Sets the value of the windChill property.
     * 
     * @param value
     *     allowed object is
     *     {@link WindChillType }
     *     
     */
    public void setWindChill(WindChillType value) {
        this.windChill = value;
    }

    /**
     * Gets the value of the visibility property.
     * 
     * @return
     *     possible object is
     *     {@link VisibilityTypeForecast }
     *     
     */
    public VisibilityTypeForecast getVisibility() {
        return visibility;
    }

    /**
     * Sets the value of the visibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisibilityTypeForecast }
     *     
     */
    public void setVisibility(VisibilityTypeForecast value) {
        this.visibility = value;
    }

    /**
     * Gets the value of the uv property.
     * 
     * @return
     *     possible object is
     *     {@link UvType }
     *     
     */
    public UvType getUv() {
        return uv;
    }

    /**
     * Sets the value of the uv property.
     * 
     * @param value
     *     allowed object is
     *     {@link UvType }
     *     
     */
    public void setUv(UvType value) {
        this.uv = value;
    }

    /**
     * Gets the value of the relativeHumidity property.
     * 
     * @return
     *     possible object is
     *     {@link RelativeHumidityType }
     *     
     */
    public RelativeHumidityType getRelativeHumidity() {
        return relativeHumidity;
    }

    /**
     * Sets the value of the relativeHumidity property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelativeHumidityType }
     *     
     */
    public void setRelativeHumidity(RelativeHumidityType value) {
        this.relativeHumidity = value;
    }

    /**
     * Gets the value of the comfort property.
     * 
     * @return
     *     possible object is
     *     {@link ComfortType }
     *     
     */
    public ComfortType getComfort() {
        return comfort;
    }

    /**
     * Sets the value of the comfort property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComfortType }
     *     
     */
    public void setComfort(ComfortType value) {
        this.comfort = value;
    }

    /**
     * Gets the value of the frost property.
     * 
     * @return
     *     possible object is
     *     {@link FrostType }
     *     
     */
    public FrostType getFrost() {
        return frost;
    }

    /**
     * Sets the value of the frost property.
     * 
     * @param value
     *     allowed object is
     *     {@link FrostType }
     *     
     */
    public void setFrost(FrostType value) {
        this.frost = value;
    }

}
