//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.15 at 12:39:23 PM ADT 
//


package com.jrodolfo.weather.model.jaxbgenerated.site;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for humidexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="humidexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="textSummary" type="{}textSummaryType"/>
 *         &lt;element name="calculated" type="{}calculatedHumidexType" maxOccurs="2" minOccurs="2"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "humidexType", propOrder = {
    "textSummary",
    "calculated"
})
public class HumidexType {

    @XmlElement(required = true)
    protected String textSummary;
    @XmlElement(required = true)
    protected List<CalculatedHumidexType> calculated;

    /**
     * Gets the value of the textSummary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextSummary() {
        return textSummary;
    }

    /**
     * Sets the value of the textSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextSummary(String value) {
        this.textSummary = value;
    }

    /**
     * Gets the value of the calculated property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the calculated property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCalculated().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CalculatedHumidexType }
     * 
     * 
     */
    public List<CalculatedHumidexType> getCalculated() {
        if (calculated == null) {
            calculated = new ArrayList<CalculatedHumidexType>();
        }
        return this.calculated;
    }

}
