//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.15 at 12:39:23 PM ADT 
//


package com.jrodolfo.weather.model.jaxbgenerated.site;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="license" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dateTime" type="{}dateStampType" maxOccurs="2" minOccurs="2"/>
 *         &lt;element name="location" type="{}locationType"/>
 *         &lt;element name="warnings" type="{}warningsType"/>
 *         &lt;element name="currentConditions" type="{}currentConditionsType"/>
 *         &lt;element name="forecastGroup" type="{}forecastGroupTypeFull"/>
 *         &lt;element name="yesterdayConditions" type="{}yesterdayConditionsType"/>
 *         &lt;element name="riseSet" type="{}riseSetType"/>
 *         &lt;element name="almanac" type="{}almanacType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "license",
    "dateTime",
    "location",
    "warnings",
    "currentConditions",
    "forecastGroup",
    "yesterdayConditions",
    "riseSet",
    "almanac"
})
@XmlRootElement(name = "siteData")
public class SiteData {

    @XmlElement(required = true)
    protected String license;
    @XmlElement(required = true)
    protected List<DateStampType> dateTime;
    @XmlElement(required = true)
    protected LocationType location;
    @XmlElement(required = true)
    protected WarningsType warnings;
    @XmlElement(required = true)
    protected CurrentConditionsType currentConditions;
    @XmlElement(required = true)
    protected ForecastGroupTypeFull forecastGroup;
    @XmlElement(required = true)
    protected YesterdayConditionsType yesterdayConditions;
    @XmlElement(required = true)
    protected RiseSetType riseSet;
    @XmlElement(required = true)
    protected AlmanacType almanac;

    /**
     * Gets the value of the license property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicense() {
        return license;
    }

    /**
     * Sets the value of the license property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicense(String value) {
        this.license = value;
    }

    /**
     * Gets the value of the dateTime property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dateTime property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDateTime().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DateStampType }
     * 
     * 
     */
    public List<DateStampType> getDateTime() {
        if (dateTime == null) {
            dateTime = new ArrayList<DateStampType>();
        }
        return this.dateTime;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link LocationType }
     *     
     */
    public LocationType getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationType }
     *     
     */
    public void setLocation(LocationType value) {
        this.location = value;
    }

    /**
     * Gets the value of the warnings property.
     * 
     * @return
     *     possible object is
     *     {@link WarningsType }
     *     
     */
    public WarningsType getWarnings() {
        return warnings;
    }

    /**
     * Sets the value of the warnings property.
     * 
     * @param value
     *     allowed object is
     *     {@link WarningsType }
     *     
     */
    public void setWarnings(WarningsType value) {
        this.warnings = value;
    }

    /**
     * Gets the value of the currentConditions property.
     * 
     * @return
     *     possible object is
     *     {@link CurrentConditionsType }
     *     
     */
    public CurrentConditionsType getCurrentConditions() {
        return currentConditions;
    }

    /**
     * Sets the value of the currentConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrentConditionsType }
     *     
     */
    public void setCurrentConditions(CurrentConditionsType value) {
        this.currentConditions = value;
    }

    /**
     * Gets the value of the forecastGroup property.
     * 
     * @return
     *     possible object is
     *     {@link ForecastGroupTypeFull }
     *     
     */
    public ForecastGroupTypeFull getForecastGroup() {
        return forecastGroup;
    }

    /**
     * Sets the value of the forecastGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForecastGroupTypeFull }
     *     
     */
    public void setForecastGroup(ForecastGroupTypeFull value) {
        this.forecastGroup = value;
    }

    /**
     * Gets the value of the yesterdayConditions property.
     * 
     * @return
     *     possible object is
     *     {@link YesterdayConditionsType }
     *     
     */
    public YesterdayConditionsType getYesterdayConditions() {
        return yesterdayConditions;
    }

    /**
     * Sets the value of the yesterdayConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesterdayConditionsType }
     *     
     */
    public void setYesterdayConditions(YesterdayConditionsType value) {
        this.yesterdayConditions = value;
    }

    /**
     * Gets the value of the riseSet property.
     * 
     * @return
     *     possible object is
     *     {@link RiseSetType }
     *     
     */
    public RiseSetType getRiseSet() {
        return riseSet;
    }

    /**
     * Sets the value of the riseSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link RiseSetType }
     *     
     */
    public void setRiseSet(RiseSetType value) {
        this.riseSet = value;
    }

    /**
     * Gets the value of the almanac property.
     * 
     * @return
     *     possible object is
     *     {@link AlmanacType }
     *     
     */
    public AlmanacType getAlmanac() {
        return almanac;
    }

    /**
     * Sets the value of the almanac property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlmanacType }
     *     
     */
    public void setAlmanac(AlmanacType value) {
        this.almanac = value;
    }

}
