//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.15 at 12:39:23 PM ADT 
//


package com.jrodolfo.weather.model.jaxbgenerated.site;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for validAccumulationNames.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="validAccumulationNames">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="snow"/>
 *     &lt;enumeration value="rain"/>
 *     &lt;enumeration value="freezing"/>
 *     &lt;enumeration value="ice pellets"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "validAccumulationNames")
@XmlEnum
public enum ValidAccumulationNames {

    @XmlEnumValue("snow")
    SNOW("snow"),
    @XmlEnumValue("rain")
    RAIN("rain"),
    @XmlEnumValue("freezing")
    FREEZING("freezing"),
    @XmlEnumValue("ice pellets")
    ICE_PELLETS("ice pellets");
    private final String value;

    ValidAccumulationNames(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ValidAccumulationNames fromValue(String v) {
        for (ValidAccumulationNames c: ValidAccumulationNames.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
