//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.15 at 12:39:23 PM ADT 
//


package com.jrodolfo.weather.model.jaxbgenerated.site;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for validTimeZones.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="validTimeZones">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ADT"/>
 *     &lt;enumeration value="AST"/>
 *     &lt;enumeration value="CDT"/>
 *     &lt;enumeration value="CST"/>
 *     &lt;enumeration value="EDT"/>
 *     &lt;enumeration value="EST"/>
 *     &lt;enumeration value="MDT"/>
 *     &lt;enumeration value="MST"/>
 *     &lt;enumeration value="NST"/>
 *     &lt;enumeration value="NDT"/>
 *     &lt;enumeration value="PDT"/>
 *     &lt;enumeration value="PST"/>
 *     &lt;enumeration value="HAA"/>
 *     &lt;enumeration value="HNA"/>
 *     &lt;enumeration value="HAC"/>
 *     &lt;enumeration value="HNC"/>
 *     &lt;enumeration value="HAE"/>
 *     &lt;enumeration value="HNE"/>
 *     &lt;enumeration value="HAR"/>
 *     &lt;enumeration value="HNR"/>
 *     &lt;enumeration value="HAT"/>
 *     &lt;enumeration value="HNT"/>
 *     &lt;enumeration value="HAP"/>
 *     &lt;enumeration value="HNP"/>
 *     &lt;enumeration value="UTC"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "validTimeZones")
@XmlEnum
public enum ValidTimeZones {

    ADT,
    AST,
    CDT,
    CST,
    EDT,
    EST,
    MDT,
    MST,
    NST,
    NDT,
    PDT,
    PST,
    HAA,
    HNA,
    HAC,
    HNC,
    HAE,
    HNE,
    HAR,
    HNR,
    HAT,
    HNT,
    HAP,
    HNP,
    UTC;

    public String value() {
        return name();
    }

    public static ValidTimeZones fromValue(String v) {
        return valueOf(v);
    }

}
