//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.15 at 12:39:23 PM ADT 
//


package com.jrodolfo.weather.model.jaxbgenerated.site;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for visibilityTypeForecast complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="visibilityTypeForecast">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="windVisib" type="{}visibilitySubTypeForecast"/>
 *         &lt;element name="otherVisib" type="{}visibilitySubTypeForecast"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "visibilityTypeForecast", propOrder = {
    "windVisib",
    "otherVisib"
})
public class VisibilityTypeForecast {

    @XmlElement(required = true)
    protected VisibilitySubTypeForecast windVisib;
    @XmlElement(required = true)
    protected VisibilitySubTypeForecast otherVisib;

    /**
     * Gets the value of the windVisib property.
     * 
     * @return
     *     possible object is
     *     {@link VisibilitySubTypeForecast }
     *     
     */
    public VisibilitySubTypeForecast getWindVisib() {
        return windVisib;
    }

    /**
     * Sets the value of the windVisib property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisibilitySubTypeForecast }
     *     
     */
    public void setWindVisib(VisibilitySubTypeForecast value) {
        this.windVisib = value;
    }

    /**
     * Gets the value of the otherVisib property.
     * 
     * @return
     *     possible object is
     *     {@link VisibilitySubTypeForecast }
     *     
     */
    public VisibilitySubTypeForecast getOtherVisib() {
        return otherVisib;
    }

    /**
     * Sets the value of the otherVisib property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisibilitySubTypeForecast }
     *     
     */
    public void setOtherVisib(VisibilitySubTypeForecast value) {
        this.otherVisib = value;
    }

}
