//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.15 at 12:39:23 PM ADT 
//


package com.jrodolfo.weather.model.jaxbgenerated.site;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for windType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="windType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="speed" type="{}windSpeedType"/>
 *         &lt;element name="gust" type="{}windSpeedType"/>
 *         &lt;element name="direction" type="{}validWindDirections"/>
 *         &lt;element name="bearing" type="{}windBearingType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="index" type="{}validWindIndices" />
 *       &lt;attribute name="rank" type="{}validWindRanks" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "windType", propOrder = {
    "speed",
    "gust",
    "direction",
    "bearing"
})
public class WindType {

    @XmlElement(required = true)
    protected WindSpeedType speed;
    @XmlElement(required = true)
    protected WindSpeedType gust;
    @XmlElement(required = true)
    protected String direction;
    @XmlElement(required = true)
    protected WindBearingType bearing;
    @XmlAttribute(name = "index")
    protected String index;
    @XmlAttribute(name = "rank")
    protected String rank;

    /**
     * Gets the value of the speed property.
     * 
     * @return
     *     possible object is
     *     {@link WindSpeedType }
     *     
     */
    public WindSpeedType getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     * 
     * @param value
     *     allowed object is
     *     {@link WindSpeedType }
     *     
     */
    public void setSpeed(WindSpeedType value) {
        this.speed = value;
    }

    /**
     * Gets the value of the gust property.
     * 
     * @return
     *     possible object is
     *     {@link WindSpeedType }
     *     
     */
    public WindSpeedType getGust() {
        return gust;
    }

    /**
     * Sets the value of the gust property.
     * 
     * @param value
     *     allowed object is
     *     {@link WindSpeedType }
     *     
     */
    public void setGust(WindSpeedType value) {
        this.gust = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirection(String value) {
        this.direction = value;
    }

    /**
     * Gets the value of the bearing property.
     * 
     * @return
     *     possible object is
     *     {@link WindBearingType }
     *     
     */
    public WindBearingType getBearing() {
        return bearing;
    }

    /**
     * Sets the value of the bearing property.
     * 
     * @param value
     *     allowed object is
     *     {@link WindBearingType }
     *     
     */
    public void setBearing(WindBearingType value) {
        this.bearing = value;
    }

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndex(String value) {
        this.index = value;
    }

    /**
     * Gets the value of the rank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRank() {
        return rank;
    }

    /**
     * Sets the value of the rank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRank(String value) {
        this.rank = value;
    }

}
