//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.15 at 12:39:23 PM ADT 
//


package com.jrodolfo.weather.model.jaxbgenerated.site;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for yesterdayConditionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="yesterdayConditionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="temperature" type="{}temperatureType" maxOccurs="2" minOccurs="2"/>
 *         &lt;element name="precip" type="{}precipType"/>
 *         &lt;element name="snowfall" type="{}snowfallType" minOccurs="0"/>
 *         &lt;element name="snowfallWaterEquiv" type="{}snowfallWaterEquivType" minOccurs="0"/>
 *         &lt;element name="rainfall" type="{}rainType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "yesterdayConditionsType", propOrder = {
    "temperature",
    "precip",
    "snowfall",
    "snowfallWaterEquiv",
    "rainfall"
})
public class YesterdayConditionsType {

    @XmlElement(required = true)
    protected List<TemperatureType> temperature;
    @XmlElement(required = true)
    protected PrecipType precip;
    protected SnowfallType snowfall;
    protected SnowfallWaterEquivType snowfallWaterEquiv;
    protected RainType rainfall;

    /**
     * Gets the value of the temperature property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the temperature property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTemperature().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TemperatureType }
     * 
     * 
     */
    public List<TemperatureType> getTemperature() {
        if (temperature == null) {
            temperature = new ArrayList<TemperatureType>();
        }
        return this.temperature;
    }

    /**
     * Gets the value of the precip property.
     * 
     * @return
     *     possible object is
     *     {@link PrecipType }
     *     
     */
    public PrecipType getPrecip() {
        return precip;
    }

    /**
     * Sets the value of the precip property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrecipType }
     *     
     */
    public void setPrecip(PrecipType value) {
        this.precip = value;
    }

    /**
     * Gets the value of the snowfall property.
     * 
     * @return
     *     possible object is
     *     {@link SnowfallType }
     *     
     */
    public SnowfallType getSnowfall() {
        return snowfall;
    }

    /**
     * Sets the value of the snowfall property.
     * 
     * @param value
     *     allowed object is
     *     {@link SnowfallType }
     *     
     */
    public void setSnowfall(SnowfallType value) {
        this.snowfall = value;
    }

    /**
     * Gets the value of the snowfallWaterEquiv property.
     * 
     * @return
     *     possible object is
     *     {@link SnowfallWaterEquivType }
     *     
     */
    public SnowfallWaterEquivType getSnowfallWaterEquiv() {
        return snowfallWaterEquiv;
    }

    /**
     * Sets the value of the snowfallWaterEquiv property.
     * 
     * @param value
     *     allowed object is
     *     {@link SnowfallWaterEquivType }
     *     
     */
    public void setSnowfallWaterEquiv(SnowfallWaterEquivType value) {
        this.snowfallWaterEquiv = value;
    }

    /**
     * Gets the value of the rainfall property.
     * 
     * @return
     *     possible object is
     *     {@link RainType }
     *     
     */
    public RainType getRainfall() {
        return rainfall;
    }

    /**
     * Sets the value of the rainfall property.
     * 
     * @param value
     *     allowed object is
     *     {@link RainType }
     *     
     */
    public void setRainfall(RainType value) {
        this.rainfall = value;
    }

}
